apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: funhouse-room-room2
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`riddler.rycr.io`) && PathPrefix(`/r/PPTMM7jeCNBP`)
      kind: Rule
      services:
        - name: funhouse-room-room2
          port: 80
      middlewares:
        - name: funhouse-room-room2-strip
  # Use Traefik entrypoint / default cert store (TLS secret stays in app ns).
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: funhouse-room-room2-strip
spec:
  stripPrefix:
    prefixes:
      - /r/PPTMM7jeCNBP
