apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: riddler-room-dev
resources:
  - stage-config.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
commonLabels:
  app.kubernetes.io/name: funhouse-room
  funhouse.riddler/room-id: room2
